### PR TITLE
BUGFIX: Use fullyqualified classname for exception

### LINKED ISSUE #18: Catching a not FQN of exception throws SQL issue in commandline
With https://github.com/Flowpack/jobqueue-doctrine/pull/17 we are able to run the setup:queue command again safely 👍 

The exception class we catch in the try/catch clause, is missing a FQN, which ends up displaying the SQLSTATE error in the command line as such

```
> /flow queue:setup default
Queue "default" has been initialized successfully.
> ./flow queue:setup default
An error occurred while trying to setup queue "default":
An exception occurred while executing 'CREATE INDEX state_scheduled ON `flowpack_jobqueue_messages_default` (state, scheduled)':

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'state_scheduled' (#0)
```

The correct FQN should be used to avoid the issue showing

### PR DESCRIPTION
**Pull request by sorenmalling**
This PR changes the exception class to be caught, to be the root Exception class of doctrine/dbal

With this change we can run the setup, with no errors shown (see related issue)

**Before**

```
> /flow queue:setup default
Queue "default" has been initialized successfully.
> ./flow queue:setup default
An error occurred while trying to setup queue "default":
An exception occurred while executing 'CREATE INDEX state_scheduled ON `flowpack_jobqueue_messages_default` (state, scheduled)':

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'state_scheduled' (#0)
```

**After**

```
> ./flow queue:setup default
Queue "default" has been initialized successfully.
> ./flow queue:setup default
Queue "default" has been initialized successfully.
```

Fixes: #18

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]

File: Classes/Queue/DoctrineQueue.php [hunk 1]
```diff
@@ -116,7 +116,7 @@ public function setUp(): void
         $this->connection->exec($createDatabaseStatement);
         try {
             $this->connection->exec("CREATE INDEX state_scheduled ON {$this->connection->quoteIdentifier($this->tableName)} (state, scheduled)");
-        } catch (Exception $e) {
+        } catch (\Doctrine\DBAL\Exception $e) {
```
Comment (bwaidelich) [inline Classes/Queue/DoctrineQueue.php]: Actually.. I think it's error prone to just silently catch all kinds of exceptions here.
Shouldn't we just catch the specific exception for the mentioned case instead?

Comment (sorenmalling) [reply Classes/Queue/DoctrineQueue.php]: Following the `exec` method, I found that it throws a `\Doctrine\DBAL\Exception` in it's method

**Review by bwaidelich — CHANGES_REQUESTED** [review]
I just gave it a try (in a Neos 5.3 installation) and `\Doctrine\DBAL\Exception` doesn't exist there. I'll check

**Comment by sorenmalling** [comment]
> I just gave it a try (in a Neos 5.3 installation) and `\Doctrine\DBAL\Exception` doesn't exist there. I'll check

What.. I'm on Flow 6.3 and have the class as this


Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Exception.php
```
<?php

namespace Doctrine\DBAL;

/**
 * @psalm-immutable
 */
class Exception extends DBALException
{
}
```

**Review by bwaidelich — APPROVED** [review]
With that version it works for me.
@sorenmalling if that works for you, feel free to merge and I'll take care of a release

File: Classes/Queue/DoctrineQueue.php (hunk 1 above)
Comment (bwaidelich) [reply Classes/Queue/DoctrineQueue.php]: It's a `Doctrine\DBAL\Exception\DriverException` for me.. But since that's not really more specific I changed it to the (already imported) `DBALException` now and that works for me

**Comment by sorenmalling** [comment]
> With that version it works for me.

I have no Neos CMS installation to test it - but composer.json says support to neos/flow 5.0. I will do some quick research before saying "yes it's fits". Will do that now

**Comment by sorenmalling** [comment]
> > With that version it works for me.
> 
> I have no Neos CMS installation to test it - but composer.json says support to neos/flow 5.0. I will do some quick research before saying "yes it's fits". Will do that now

And yes.. In neos/flow we require doctrine/dbal ~2.7.0 where the "root" excepton didn't exists, but the DBALException did instead (which is extended today, by the "root" exception.

https://github.com/doctrine/dbal/blob/2.7/lib/Doctrine/DBAL/DBALException.php

Will adjust exception class

**Comment by sorenmalling** [comment]
Arh, I see you already did that in the commits :D

**Comment by sorenmalling** [comment]
> feel free to merge and I'll take care of a release

I don't seem to have write access to this repository to do that

**Comment by bwaidelich** [comment]
Done. Thanks a lot for the fix!
