### PR TITLE
BUGFIX: Make it safe to run setup more than once

### LINKED ISSUE #12: Duplicate key name 'state_scheduled' error
We've always been running the `flow setup:queue <queue name>` command on all deploys to be sure the required queues for an application actually exist.

Since 3.0.2 this throws an exception about a duplicate key name 'state_scheduled'. Looking at the code the whole setUp() methods uses `IF NOT EXISTS` for table creation, but the index is always created.

I just tried using `CREATE INDEX IF NOT EXISTS...`  and that seems to fix the issue, but I can't find that in the mysql docs so I assume that's a mariadb feature (I'm at `10.3.14-MariaDB-1:10.3.14+maria~bionic`)

Before calling this a real bug: should it be safe to re-run the setup for a queue?

### PR DESCRIPTION
**Pull request by albe**
There is no `CREATE INDEX IF NOT EXISTS` in MySql, so we need to try/catch to make the operation optional.
See https://dba.stackexchange.com/questions/24531/mysql-create-index-if-not-exists
Fixes #12

### CODE REVIEW

**Review by markusguenther — APPROVED** [review]
Great, thanks for taking care @albe :)

**Review by daniellienert — APPROVED** [review]

File: Classes/Queue/DoctrineQueue.php [hunk 1]
```diff
@@ -114,7 +114,11 @@ public function setUp(): void
                 $createDatabaseStatement = "CREATE TABLE IF NOT EXISTS {$this->connection->quoteIdentifier($this->tableName)} (id INTEGER PRIMARY KEY AUTO_INCREMENT, payload LONGTEXT NOT NULL, state VARCHAR(255) NOT NULL, failures INTEGER NOT NULL DEFAULT 0, scheduled DATETIME DEFAULT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB";
         }
         $this->connection->exec($createDatabaseStatement);
-        $this->connection->exec("CREATE INDEX state_scheduled ON {$this->connection->quoteIdentifier($this->tableName)} (state, scheduled)");
+        try {
+            $this->connection->exec("CREATE INDEX state_scheduled ON {$this->connection->quoteIdentifier($this->tableName)} (state, scheduled)");
+        } catch (Exception $e) {
+            // See https://dba.stackexchange.com/questions/24531/mysql-create-index-if-not-exists
```
Comment (bwaidelich) [inline Classes/Queue/DoctrineQueue.php:120]: IMO it's a dangerous pattern to just silently ignore a whole class of exceptions.. IMO we should just catch the exact exception class for the described case and (in the long run) allow the setup to report back
